AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation to setup the ec2 backup process. This takes backup of ebs
  volume which are tagged with Backup and does the deletion of older snapshots
Parameters:
 AutoscalingGroupName:
  Description: 'Name of the autoscaling group'
  Type: String
  Default: WebServerASG01
Resources:
  EC2SnapshotInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2SnapshotRole
  EC2SnapshotPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: EC2SnapshotPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:CreateSnapshot'
              - 'ec2:DeleteSnapshot'
              - 'ec2:CreateTags'
              - 'ec2:ModifySnapshotAttribute'
              - 'ec2:ResetSnapshotAttribute'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeSnapshots'
              - 'autoscaling:*'
              - 'logs:PutLogEvents'
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
            Resource: '*'
      Roles:
        - !Ref EC2SnapshotRole
  EC2SnapshotRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: ADSK-lambda-ec2-backup-job-role
      Path: /
  AutoscalingGroupUpdate:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      FunctionName: autoscaling_group_update
      Role: !GetAtt 
        - EC2SnapshotRole
        - Arn
      Code:
        S3Bucket: sudsanka2019
        S3Key: update_asg_ebs_snapshot.zip
      Runtime: python3.7
      Timeout: 300
      Environment:
        Variables:
          ASG_NAME: !Ref 'AutoscalingGroupName'
  ScheduledRule1:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: ebsdailybackup
      ScheduleExpression: cron(15 12 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt 
            - AutoscalingGroupUpdate
            - Arn
          Id: TargetFunctionV1
  PermissionForEventsToInvokeLambda1:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref AutoscalingGroupUpdate
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 
        - ScheduledRule1
        - Arn
